export const YEARS = [
  '1st Year',
  '2nd Year',
  '3rd Year',
  '4th Year',
];

export const COURSES = [
  'BS ACCOUNTANCY',
  'BS HOSPITALITY MANAGEMENT',
  'BS TOURISM MANAGEMENT',
  'BSBA- MARKETING MANAGEMENT',
  'BSBA- BANKING & MICROFINANCE',
  'BACHELOR OF ELEMENTARY EDUCATION',
  'BSED- ENGLISH',
  'BSED- FILIPINO',
  'BS CRIMINOLOGY',
  'BS CIVIL ENGINEERING',
  'BS INFORMATION TECHNOLOGY',
  'BS NURSING',
];

